Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.define "mongodb" do |mongodb|
    mongodb.vm.hostname = "deb-buster64-mongodb-44-vbox"
    mongodb.vm.network "private_network", ip: "192.168.10.200"
    mongodb.vm.provider "virtualbox" do |vb|
      vb.name = "deb-buster64-mongodb-44-vbox"
    end
    mongodb.vm.provision "file", source: "mongod.conf", destination: "/tmp/mongod.conf"
    mongodb.vm.provision "file", source: "add_mongo_admin.js", destination: "/tmp/add_mongo_admin.js"
    mongodb.vm.provision "file", source: "update.sh", destination: "/tmp/update.sh"
    mongodb.vm.provision "shell", path: "install_mongodb-4.4.sh"
  end
end
